services:
  beam_postgres:
    image: postgres:14
    container_name: beam_postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beam_test
    ports:
      - "5432:5432"
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql

  beam_runner:
    build: .
    depends_on:
      - beam_postgres
    environment:
      PGHOST: beam_postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: beam_test
      PGPORT: "5432"
    volumes:
      - ./:/app

